import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <header>
            <nav>
              <ul>
                <li>
                  <a href="/employee">empleados</a>
                </li>
                <li>
                  <a href="/contratos">contratos</a>
                </li>
              </ul>
            </nav>
          </header>
        </div>
        {children}
        </body>
    </html>
  );
}
